### ISSUE TITLE
simplify

### ISSUE THREAD

**Issue by aric87** [mse2321/xp-calculator#13]
You're checking for falsey values, so instead of checking each individually, just check if it's false
https://github.com/mse2321/xp-calculator/blob/master/index.html#L156

`if $scope.xp < 0 || !$scope.xp`

**Comment by aric87** [comment]
same here: https://github.com/mse2321/xp-calculator/blob/master/index.html#L153

**Comment by aric87** [comment]
and here; https://github.com/mse2321/xp-calculator/blob/master/index.html#L159

**Comment by mse2321** [comment]
Done
