### ISSUE TITLE
put this in a separate file

### ISSUE THREAD

**Issue by aric87** [mse2321/xp-calculator#2]
https://github.com/mse2321/xp-calculator/blob/master/index.html#L25
inline style tags should only be used if you absolutely must. Some people work this way, but most companies don't.

**Comment by aric87** [comment]
Same thing here. Inline script tags aren't going to help you in an interview
https://github.com/mse2321/xp-calculator/blob/master/index.html#L131

**Comment by mse2321** [comment]
Done
